"""Cross-validation test for JS/Python narrative parity.

Verifies that narrative strings in narrative_engine.py appear identically
in personalization.js. Catches drift if either file is edited independently.

Reference: abc-assessment-spec Section 3
"""

from pathlib import Path

import pytest

from src.python_scoring.narrative_engine import NarrativeEngine

JS_FILE = Path(__file__).parent.parent.parent / "outputs" / "site" / "personalization.js"

ARCHETYPES = [
    "Integrator",
    "Captain",
    "Architect",
    "Mentor",
    "Pioneer",
    "Anchor",
    "Artisan",
    "Seeker",
]

SIGNATURES = [
    "Blocked Drive",
    "Conditional Belonging",
    "Evaluated Mastery",
    "Controlled Motivation",
    "Active Exclusion",
    "Competence Threat",
]


@pytest.fixture(scope="module")
def engine():
    return NarrativeEngine()


@pytest.fixture(scope="module")
def js_content():
    if not JS_FILE.exists():
        pytest.skip("personalization.js not found (dashboard not built)")
    return JS_FILE.read_text(encoding="utf-8")


class TestArchetypeNarrativeParity:
    """Verify archetype narratives match between Python and JS.

    Known status: JS narratives were independently generated by a separate
    agent and have minor wording differences from the Python source.
    These tests are marked xfail until the JS is synced from Python
    (Phase 3, Gap 1 of the fix plan).
    """

    @pytest.mark.xfail(reason="JS narratives independently generated, sync pending")
    def test_athlete_identity_descriptions_in_js(self, engine, js_content):
        """Every athlete identity_description from Python must appear in JS."""
        missing = []
        for archetype in ARCHETYPES:
            narr = engine.generate_archetype_narrative(archetype, "athlete")
            desc = narr["identity_description"]
            # Check a substantial substring (first 80 chars) rather than
            # exact match, to allow for JS string concatenation differences
            check = desc[:80]
            if check not in js_content:
                missing.append(archetype)
        assert not missing, f"Athlete identity descriptions missing from JS for: {missing}"

    @pytest.mark.xfail(reason="JS narratives independently generated, sync pending")
    def test_coach_identity_descriptions_in_js(self, engine, js_content):
        """Every coach identity_description from Python must appear in JS."""
        missing = []
        for archetype in ARCHETYPES:
            narr = engine.generate_archetype_narrative(archetype, "coach")
            desc = narr["identity_description"]
            check = desc[:80]
            if check not in js_content:
                missing.append(archetype)
        assert not missing, f"Coach identity descriptions missing from JS for: {missing}"

    @pytest.mark.xfail(reason="JS narratives independently generated, sync pending")
    def test_all_archetypes_have_strengths_in_js(self, engine, js_content):
        """Each archetype's first strength should appear in JS."""
        missing = []
        for archetype in ARCHETYPES:
            narr = engine.generate_archetype_narrative(archetype, "athlete")
            if narr.get("strengths"):
                first_strength = narr["strengths"][0][:60]
                if first_strength not in js_content:
                    missing.append(archetype)
        assert not missing, f"First strength missing from JS for: {missing}"


class TestSignatureNarrativeParity:
    """Verify frustration signature narratives match between Python and JS."""

    @pytest.mark.xfail(reason="JS narratives independently generated, sync pending")
    def test_athlete_signature_descriptions_in_js(self, engine, js_content):
        """Every athlete signature description from Python must appear in JS."""
        missing = []
        for label in SIGNATURES:
            sig = {"label": label, "domain": "ambition", "risk": "medium"}
            narr = engine.generate_signature_narrative(sig, "athlete")
            check = narr["description"][:60]
            if check not in js_content:
                missing.append(label)
        assert not missing, f"Athlete signature descriptions missing from JS for: {missing}"


class TestDisclosureParity:
    """Verify measurement disclosure text matches between Python and JS.

    JS uses template placeholders ({count}, {s}) that are filled at runtime,
    so we check for the static portion of each disclosure tier.
    """

    def test_early_disclosure_fragment_in_js(self, js_content):
        """Early tier disclosure template must exist in JS."""
        # The static portion after the count placeholder
        assert "starting point, not a verdict" in js_content

    def test_developing_disclosure_fragment_in_js(self, js_content):
        """Developing tier disclosure template must exist in JS."""
        assert "The picture is" in js_content

    def test_established_disclosure_fragment_in_js(self, js_content):
        """Established tier disclosure template must exist in JS."""
        assert "well calibrated" in js_content
